- organization: a
  week: 1
  maximum: 7
  available: 7
- organization: a
  week: 2
  maximum: 7
  available: 7
- organization: a
  week: 3
  maximum: 7
  available: 7
- organization: a
  week: 4
  maximum: 7
  available: 7
- organization: a
  week: 5
  maximum: 0
  available: 0
- organization: a
  week: 6
  maximum: 7
  available: 7
- organization: a
  week: 7
  maximum: 7
  available: 7
- organization: a
  week: 8
  maximum: 0
  available: 0
- organization: a
  week: 9
  maximum: 0
  available: 0
- organization: a
  week: 10
  maximum: 7
  available: 7
- organization: c
  week: 1
  maximum: 5
  available: 5
- organization: c
  week: 2
  maximum: 5
  available: 5
- organization: c
  week: 3
  maximum: 5
  available: 5
- organization: c
  week: 4
  maximum: 0
  available: 0
- organization: c
  week: 5
  maximum: 5
  available: 5
- organization: c
  week: 6
  maximum: 5
  available: 5
- organization: c
  week: 7
  maximum: 5
  available: 5
- organization: c
  week: 8
  maximum: 5
  available: 5
- organization: c
  week: 9
  maximum: 5
  available: 5
- organization: c
  week: 10
  maximum: 5
  available: 5
- organization: j
  week: 1
  maximum: 7
  available: 7
- organization: j
  week: 2
  maximum: 7
  available: 7
- organization: j
  week: 3
  maximum: 7
  available: 7
- organization: j
  week: 4
  maximum: 7
  available: 7
- organization: j
  week: 5
  maximum: 0
  available: 0
- organization: j
  week: 6
  maximum: 7
  available: 7
- organization: j
  week: 7
  maximum: 7
  available: 7
- organization: j
  week: 8
  maximum: 14
  available: 14
- organization: j
  week: 9
  maximum: 0
  available: 0
- organization: j
  week: 10
  maximum: 14
  available: 14
- organization: t
  week: 1
  maximum: 10
  available: 10
- organization: t
  week: 2
  maximum: 10
  available: 10
- organization: t
  week: 3
  maximum: 5
  available: 5
- organization: t
  week: 4
  maximum: 5
  available: 5
- organization: t
  week: 5
  maximum: 5
  available: 5
- organization: t
  week: 6
  maximum: 5
  available: 5
- organization: t
  week: 7
  maximum: 5
  available: 5
- organization: t
  week: 8
  maximum: 5
  available: 5
- organization: t
  week: 9
  maximum: 5
  available: 5
- organization: t
  week: 10
  maximum: 5
  available: 5
- organization: y
  week: 1
  maximum: 4
  available: 4
- organization: y
  week: 2
  maximum: 4
  available: 4
- organization: y
  week: 3
  maximum: 4
  available: 4
- organization: y
  week: 4
  maximum: 4
  available: 4
- organization: y
  week: 5
  maximum: 5
  available: 5
- organization: y
  week: 6
  maximum: 5
  available: 5
- organization: y
  week: 7
  maximum: 5
  available: 5
- organization: y
  week: 8
  maximum: 5
  available: 5
- organization: y
  week: 9
  maximum: 4
  available: 4
- organization: y
  week: 10
  maximum: 4
  available: 4
